required = [
  "github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator",
  "github.com/vektra/mockery/cmd/mockery",
]

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.14.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kubicorn/kubicorn"
  branch = "master"


[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.8"


[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.8"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.8"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  name = "k8s.io/kops"
  branch = "master"

[[constraint]]
  name = "github.com/kubernetes-sigs/aws-iam-authenticator"
  branch = "master"

[[constraint]]
  name = "github.com/weaveworks/launcher"
  branch = "master"

[[constraint]]
  name = "github.com/kballard/go-shellquote"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/vektra/mockery"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/dlespiau/kube-test-harness"
  branch = "master"

[[constraint]]
   name = "github.com/awslabs/goformation"
   source = "https://github.com/errordeveloper/goformation"
   branch = "pin-eksctl"

[[constraint]]
  name = "github.com/dave/jennifer"
  version = "v1.1.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
